# Generated by rspec-sinatra. (2015-09-21 11:00:19 +0200)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', 'lib/my_app.rb')

require 'capybara'
require 'capybara/rspec'
require 'rspec'
require 'dm-rspec'
require 'pry'
require 'database_cleaner'


def app
  MyApp
end

Capybara.app = MyApp

RSpec.configure do |config|
  config.include Capybara::DSL
  config.include Rack::Test::Methods
  config.include(DataMapper::Matchers)
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
  
  config.before(:suite) do
  		DatabaseCleaner.strategy = :transaction
  		DatabaseCleaner.clean_with(:truncation)
  end
  
  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
  	DatabaseCleaner.clean
  end

end
